import type { FlatTokenMap } from "./types";

export const componentTokens: FlatTokenMap = {
  "button.height.sm": "32px",
  "button.height.md": "40px",
  "button.height.lg": "48px",
  "button.radius": "10px",
  "button.solid.bg": "var(--aurora-accent-default)",
  "button.solid.bg-hover": "var(--aurora-accent-hover)",
  "button.solid.text": "var(--aurora-text-inverse)",
  "button.ghost.bg": "transparent",
  "button.ghost.text": "var(--aurora-text-primary)",
  "button.border": "var(--aurora-border-default)",
  "input.height": "40px",
  "input.radius": "10px",
  "input.bg": "var(--aurora-surface-elevated)",
  "input.text": "var(--aurora-text-primary)",
  "input.placeholder": "var(--aurora-text-secondary)",
  "input.border": "var(--aurora-border-default)",
  "input.focus-ring": "var(--aurora-focus-ring)",
  "overlay.bg": "rgba(2, 6, 23, 0.45)",
  "overlay.blur": "2px",
  "panel.bg": "var(--aurora-surface-overlay)",
  "panel.border": "var(--aurora-border-default)",
  "panel.shadow": "var(--aurora-shadow-md)",
  "skeleton.base": "rgba(148, 163, 184, 0.18)",
  "skeleton.highlight": "rgba(148, 163, 184, 0.32)",
  "streaming.cursor": "var(--aurora-accent-default)",
  "feedback.info.bg": "color-mix(in srgb, var(--aurora-color-cyan-500) 12%, transparent)",
  "feedback.info.border": "color-mix(in srgb, var(--aurora-color-cyan-500) 30%, transparent)",
  "feedback.info.text": "color-mix(in srgb, var(--aurora-color-cyan-500) 80%, var(--aurora-text-primary))",
  "feedback.success.bg": "color-mix(in srgb, var(--aurora-color-green-500) 12%, transparent)",
  "feedback.success.border": "color-mix(in srgb, var(--aurora-color-green-500) 30%, transparent)",
  "feedback.success.text": "color-mix(in srgb, var(--aurora-color-green-500) 78%, var(--aurora-text-primary))",
  "feedback.warning.bg": "color-mix(in srgb, var(--aurora-color-amber-500) 14%, transparent)",
  "feedback.warning.border": "color-mix(in srgb, var(--aurora-color-amber-500) 32%, transparent)",
  "feedback.warning.text": "color-mix(in srgb, var(--aurora-color-amber-500) 80%, var(--aurora-text-primary))",
  "feedback.danger.bg": "color-mix(in srgb, var(--aurora-color-red-500) 14%, transparent)",
  "feedback.danger.border": "color-mix(in srgb, var(--aurora-color-red-500) 32%, transparent)",
  "feedback.danger.text": "color-mix(in srgb, var(--aurora-color-red-500) 80%, var(--aurora-text-primary))"
};
